server:
  port: 8085

spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: validate

jasypt:
  encryptor:
    password: ${jasypt_key}
    bean: jasyptEncryptor

app:
  kafka:
    topic:
      notification: match.notification.requested
    group-id:
      notification: notification.alert.sender

jdbc:
  batch:
    size: 1000
