server:
  port: 8081

spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: validate

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(dDFakmi/a0d7f5V6UdW7q9tBuKZYEqdVK5fCFxPGlVI=)
    password: ENC(UBKt8Z9GLNO3+6hqOBKBElzaysOyIqxHXrVwNG7clB8=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
    max_attempts: 5
    lock_minutes: 15
    expire_minutes: 5

jasypt:
  encryptor:
    password: ${jasypt_key}
    bean: jasyptEncryptor

jwt:
  secret: ${jwt_key}
  expiration_time: 600000              # 10분
  refresh_expiration_time: 1209600000  # 14일

app:
  limits:
    keyword-max-count: 20
    folder-max-count: 7
