spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/key_feed_identity?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1111

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${jwt_key}
  expiration_time: 60000000            # 10분
  refresh_expiration_time: 1209600000  # 14일

logging:
  level:
    p6spy: info
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
