server:
  port: 8000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-auth-service
              uri: lb://identity-service
              predicates:
                - Path=/api/auth/**
            - id: identity-bookmark-service
              uri: lb://identity-service
              predicates:
                - Path=/api/bookmarks/**
              filters:
                - JwtAuthenticationFilter
            - id: identity-service
              uri: lb://identity-service
              predicates:
                - Path=/api/keywords/**
              filters:
                - JwtAuthenticationFilter
            - id: feed-service
              uri: lb://feed-service
              predicates:
                - Path=/api/feed/**
              filters:
                - JwtAuthenticationFilter
            - id: identity-service-source
              uri: lb://identity-service
              predicates:
                - Path=/api/sources/**
              filters:
                - JwtAuthenticationFilter
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notifications/**
              filters:
                - JwtAuthenticationFilter
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: 'http://localhost:5173'
                allow-credentials: true
                allowedHeaders: '*'
                allowedMethods:
                  - PUT
                  - GET
                  - POST
                  - DELETE
                  - OPTIONS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${jwt_key}