server:
  port: 8084

spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: validate

jasypt:
  encryptor:
    password: ${jasypt_key}
    bean: jasyptEncryptor

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

client:
  identity-service:
    access-url: http://identity-service

app:
  kafka:
    topic:
      content: crawl.content.collected
      notification: match.notification.requested

snowflake:
  worker-id: 1
  datacenter-id: 1
